// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ingester.proto

package ingester

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLogReq) Reset() {
	*x = WriteLogReq{}
	mi := &file_ingester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLogReq) ProtoMessage() {}

func (x *WriteLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLogReq.ProtoReflect.Descriptor instead.
func (*WriteLogReq) Descriptor() ([]byte, []int) {
	return file_ingester_proto_rawDescGZIP(), []int{0}
}

func (x *WriteLogReq) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLogResp) Reset() {
	*x = WriteLogResp{}
	mi := &file_ingester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLogResp) ProtoMessage() {}

func (x *WriteLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLogResp.ProtoReflect.Descriptor instead.
func (*WriteLogResp) Descriptor() ([]byte, []int) {
	return file_ingester_proto_rawDescGZIP(), []int{1}
}

func (x *WriteLogResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_ingester_proto protoreflect.FileDescriptor

const file_ingester_proto_rawDesc = "" +
	"\n" +
	"\x0eingester.proto\x12\bingester\x1a\x1cgoogle/protobuf/struct.proto\":\n" +
	"\vWriteLogReq\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"&\n" +
	"\fWriteLogResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2H\n" +
	"\vLogIngester\x129\n" +
	"\bWriteLog\x12\x15.ingester.WriteLogReq\x1a\x16.ingester.WriteLogRespB\x10Z\x0etypes/ingesterb\x06proto3"

var (
	file_ingester_proto_rawDescOnce sync.Once
	file_ingester_proto_rawDescData []byte
)

func file_ingester_proto_rawDescGZIP() []byte {
	file_ingester_proto_rawDescOnce.Do(func() {
		file_ingester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingester_proto_rawDesc), len(file_ingester_proto_rawDesc)))
	})
	return file_ingester_proto_rawDescData
}

var file_ingester_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ingester_proto_goTypes = []any{
	(*WriteLogReq)(nil),     // 0: ingester.WriteLogReq
	(*WriteLogResp)(nil),    // 1: ingester.WriteLogResp
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_ingester_proto_depIdxs = []int32{
	2, // 0: ingester.WriteLogReq.data:type_name -> google.protobuf.Struct
	0, // 1: ingester.LogIngester.WriteLog:input_type -> ingester.WriteLogReq
	1, // 2: ingester.LogIngester.WriteLog:output_type -> ingester.WriteLogResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ingester_proto_init() }
func file_ingester_proto_init() {
	if File_ingester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingester_proto_rawDesc), len(file_ingester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingester_proto_goTypes,
		DependencyIndexes: file_ingester_proto_depIdxs,
		MessageInfos:      file_ingester_proto_msgTypes,
	}.Build()
	File_ingester_proto = out.File
	file_ingester_proto_goTypes = nil
	file_ingester_proto_depIdxs = nil
}
