// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: ingester.proto

package ingester

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIngester_WriteLog_FullMethodName = "/ingester.LogIngester/WriteLog"
)

// LogIngesterClient is the client API for LogIngester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogIngesterClient interface {
	WriteLog(ctx context.Context, in *WriteLogReq, opts ...grpc.CallOption) (*WriteLogResp, error)
}

type logIngesterClient struct {
	cc grpc.ClientConnInterface
}

func NewLogIngesterClient(cc grpc.ClientConnInterface) LogIngesterClient {
	return &logIngesterClient{cc}
}

func (c *logIngesterClient) WriteLog(ctx context.Context, in *WriteLogReq, opts ...grpc.CallOption) (*WriteLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteLogResp)
	err := c.cc.Invoke(ctx, LogIngester_WriteLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogIngesterServer is the server API for LogIngester service.
// All implementations must embed UnimplementedLogIngesterServer
// for forward compatibility.
type LogIngesterServer interface {
	WriteLog(context.Context, *WriteLogReq) (*WriteLogResp, error)
	mustEmbedUnimplementedLogIngesterServer()
}

// UnimplementedLogIngesterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogIngesterServer struct{}

func (UnimplementedLogIngesterServer) WriteLog(context.Context, *WriteLogReq) (*WriteLogResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteLog not implemented")
}
func (UnimplementedLogIngesterServer) mustEmbedUnimplementedLogIngesterServer() {}
func (UnimplementedLogIngesterServer) testEmbeddedByValue()                     {}

// UnsafeLogIngesterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogIngesterServer will
// result in compilation errors.
type UnsafeLogIngesterServer interface {
	mustEmbedUnimplementedLogIngesterServer()
}

func RegisterLogIngesterServer(s grpc.ServiceRegistrar, srv LogIngesterServer) {
	// If the following call panics, it indicates UnimplementedLogIngesterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIngester_ServiceDesc, srv)
}

func _LogIngester_WriteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogIngesterServer).WriteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogIngester_WriteLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogIngesterServer).WriteLog(ctx, req.(*WriteLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LogIngester_ServiceDesc is the grpc.ServiceDesc for LogIngester service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIngester_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingester.LogIngester",
	HandlerType: (*LogIngesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLog",
			Handler:    _LogIngester_WriteLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingester.proto",
}
