// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"log-system-backend/application/log-api/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/log/search",
				Handler: SearchLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/log/write",
				Handler: WriteLogHandler(serverCtx),
			},
		},
	)
}
