// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user_auth.proto

package auth

import (
	"context"

	"log-system-backend/application/user-auth/rpc/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AppInfo                 = auth.AppInfo
	CreateAppRequest        = auth.CreateAppRequest
	CreateAppResponse       = auth.CreateAppResponse
	DeleteAppRequest        = auth.DeleteAppRequest
	DeleteAppResponse       = auth.DeleteAppResponse
	GetAppRequest           = auth.GetAppRequest
	GetAppResponse          = auth.GetAppResponse
	ListAppsRequest         = auth.ListAppsRequest
	ListAppsResponse        = auth.ListAppsResponse
	LoginRequest            = auth.LoginRequest
	LoginResponse           = auth.LoginResponse
	RegisterRequest         = auth.RegisterRequest
	RegisterResponse        = auth.RegisterResponse
	UpdateAppRequest        = auth.UpdateAppRequest
	UpdateAppResponse       = auth.UpdateAppResponse
	ValidateTokenRequest    = auth.ValidateTokenRequest
	ValidateTokenResponse   = auth.ValidateTokenResponse
	VerifyAppAccessRequest  = auth.VerifyAppAccessRequest
	VerifyAppAccessResponse = auth.VerifyAppAccessResponse
	VerifyAppSecretRequest  = auth.VerifyAppSecretRequest
	VerifyAppSecretResponse = auth.VerifyAppSecretResponse

	Auth interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
		// App management
		CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
		UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*UpdateAppResponse, error)
		DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*DeleteAppResponse, error)
		GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error)
		ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
		VerifyAppAccess(ctx context.Context, in *VerifyAppAccessRequest, opts ...grpc.CallOption) (*VerifyAppAccessResponse, error)
		VerifyAppSecret(ctx context.Context, in *VerifyAppSecretRequest, opts ...grpc.CallOption) (*VerifyAppSecretResponse, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

func (m *defaultAuth) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAuth) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuth) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

// App management
func (m *defaultAuth) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.CreateApp(ctx, in, opts...)
}

func (m *defaultAuth) UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*UpdateAppResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.UpdateApp(ctx, in, opts...)
}

func (m *defaultAuth) DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*DeleteAppResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.DeleteApp(ctx, in, opts...)
}

func (m *defaultAuth) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.GetApp(ctx, in, opts...)
}

func (m *defaultAuth) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.ListApps(ctx, in, opts...)
}

func (m *defaultAuth) VerifyAppAccess(ctx context.Context, in *VerifyAppAccessRequest, opts ...grpc.CallOption) (*VerifyAppAccessResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.VerifyAppAccess(ctx, in, opts...)
}

func (m *defaultAuth) VerifyAppSecret(ctx context.Context, in *VerifyAppSecretRequest, opts ...grpc.CallOption) (*VerifyAppSecretResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.VerifyAppSecret(ctx, in, opts...)
}
