// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user_auth.proto

package server

import (
	"context"

	"log-system-backend/application/user-auth/rpc/auth"
	"log-system-backend/application/user-auth/rpc/internal/logic"
	"log-system-backend/application/user-auth/rpc/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) Register(ctx context.Context, in *auth.RegisterRequest) (*auth.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServer) Login(ctx context.Context, in *auth.LoginRequest) (*auth.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServer) ValidateToken(ctx context.Context, in *auth.ValidateTokenRequest) (*auth.ValidateTokenResponse, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

// App management
func (s *AuthServer) CreateApp(ctx context.Context, in *auth.CreateAppRequest) (*auth.CreateAppResponse, error) {
	l := logic.NewCreateAppLogic(ctx, s.svcCtx)
	return l.CreateApp(in)
}

func (s *AuthServer) UpdateApp(ctx context.Context, in *auth.UpdateAppRequest) (*auth.UpdateAppResponse, error) {
	l := logic.NewUpdateAppLogic(ctx, s.svcCtx)
	return l.UpdateApp(in)
}

func (s *AuthServer) DeleteApp(ctx context.Context, in *auth.DeleteAppRequest) (*auth.DeleteAppResponse, error) {
	l := logic.NewDeleteAppLogic(ctx, s.svcCtx)
	return l.DeleteApp(in)
}

func (s *AuthServer) GetApp(ctx context.Context, in *auth.GetAppRequest) (*auth.GetAppResponse, error) {
	l := logic.NewGetAppLogic(ctx, s.svcCtx)
	return l.GetApp(in)
}

func (s *AuthServer) ListApps(ctx context.Context, in *auth.ListAppsRequest) (*auth.ListAppsResponse, error) {
	l := logic.NewListAppsLogic(ctx, s.svcCtx)
	return l.ListApps(in)
}

func (s *AuthServer) VerifyAppAccess(ctx context.Context, in *auth.VerifyAppAccessRequest) (*auth.VerifyAppAccessResponse, error) {
	l := logic.NewVerifyAppAccessLogic(ctx, s.svcCtx)
	return l.VerifyAppAccess(in)
}
