// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: query.proto

package logquery

import (
	"context"

	"log-system-backend/application/log-query/rpc/types/query"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LogItem       = query.LogItem
	SearchLogReq  = query.SearchLogReq
	SearchLogResp = query.SearchLogResp

	LogQuery interface {
		SearchLog(ctx context.Context, in *SearchLogReq, opts ...grpc.CallOption) (*SearchLogResp, error)
	}

	defaultLogQuery struct {
		cli zrpc.Client
	}
)

func NewLogQuery(cli zrpc.Client) LogQuery {
	return &defaultLogQuery{
		cli: cli,
	}
}

func (m *defaultLogQuery) SearchLog(ctx context.Context, in *SearchLogReq, opts ...grpc.CallOption) (*SearchLogResp, error) {
	client := query.NewLogQueryClient(m.cli.Conn())
	return client.SearchLog(ctx, in, opts...)
}
