// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: query.proto

package server

import (
	"context"

	"log-system-backend/application/log-query/rpc/internal/logic"
	"log-system-backend/application/log-query/rpc/internal/svc"
	"log-system-backend/application/log-query/rpc/types/query"
)

type LogQueryServer struct {
	svcCtx *svc.ServiceContext
	query.UnimplementedLogQueryServer
}

func NewLogQueryServer(svcCtx *svc.ServiceContext) *LogQueryServer {
	return &LogQueryServer{
		svcCtx: svcCtx,
	}
}

func (s *LogQueryServer) SearchLog(ctx context.Context, in *query.SearchLogReq) (*query.SearchLogResp, error) {
	l := logic.NewSearchLogLogic(ctx, s.svcCtx)
	return l.SearchLog(in)
}
