// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogQuery_SearchLog_FullMethodName = "/query.LogQuery/SearchLog"
)

// LogQueryClient is the client API for LogQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogQueryClient interface {
	SearchLog(ctx context.Context, in *SearchLogReq, opts ...grpc.CallOption) (*SearchLogResp, error)
}

type logQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewLogQueryClient(cc grpc.ClientConnInterface) LogQueryClient {
	return &logQueryClient{cc}
}

func (c *logQueryClient) SearchLog(ctx context.Context, in *SearchLogReq, opts ...grpc.CallOption) (*SearchLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLogResp)
	err := c.cc.Invoke(ctx, LogQuery_SearchLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogQueryServer is the server API for LogQuery service.
// All implementations must embed UnimplementedLogQueryServer
// for forward compatibility.
type LogQueryServer interface {
	SearchLog(context.Context, *SearchLogReq) (*SearchLogResp, error)
	mustEmbedUnimplementedLogQueryServer()
}

// UnimplementedLogQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogQueryServer struct{}

func (UnimplementedLogQueryServer) SearchLog(context.Context, *SearchLogReq) (*SearchLogResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchLog not implemented")
}
func (UnimplementedLogQueryServer) mustEmbedUnimplementedLogQueryServer() {}
func (UnimplementedLogQueryServer) testEmbeddedByValue()                  {}

// UnsafeLogQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogQueryServer will
// result in compilation errors.
type UnsafeLogQueryServer interface {
	mustEmbedUnimplementedLogQueryServer()
}

func RegisterLogQueryServer(s grpc.ServiceRegistrar, srv LogQueryServer) {
	// If the following call panics, it indicates UnimplementedLogQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogQuery_ServiceDesc, srv)
}

func _LogQuery_SearchLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogQueryServer).SearchLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogQuery_SearchLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogQueryServer).SearchLog(ctx, req.(*SearchLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LogQuery_ServiceDesc is the grpc.ServiceDesc for LogQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.LogQuery",
	HandlerType: (*LogQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchLog",
			Handler:    _LogQuery_SearchLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query.proto",
}
