// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ingester.proto

package server

import (
	"context"

	"log-system-backend/application/log-ingester/rpc/internal/logic"
	"log-system-backend/application/log-ingester/rpc/internal/svc"
	"log-system-backend/application/log-ingester/rpc/types/ingester"
)

type LogIngesterServer struct {
	svcCtx *svc.ServiceContext
	ingester.UnimplementedLogIngesterServer
}

func NewLogIngesterServer(svcCtx *svc.ServiceContext) *LogIngesterServer {
	return &LogIngesterServer{
		svcCtx: svcCtx,
	}
}

func (s *LogIngesterServer) WriteLog(ctx context.Context, in *ingester.WriteLogReq) (*ingester.WriteLogResp, error) {
	l := logic.NewWriteLogLogic(ctx, s.svcCtx)
	return l.WriteLog(in)
}
