// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type WriteLogReq struct {
	Source  string `json:"source"`
	Level   string `json:"level"`
	Content string `json:"content"`
}

type WriteLogResp struct {
	Ok bool `json:"ok"`
}
