// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ingester.proto

package logingester

import (
	"context"

	"log-system-backend/application/log-ingester/rpc/types/ingester"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WriteLogReq  = ingester.WriteLogReq
	WriteLogResp = ingester.WriteLogResp

	LogIngester interface {
		WriteLog(ctx context.Context, in *WriteLogReq, opts ...grpc.CallOption) (*WriteLogResp, error)
	}

	defaultLogIngester struct {
		cli zrpc.Client
	}
)

func NewLogIngester(cli zrpc.Client) LogIngester {
	return &defaultLogIngester{
		cli: cli,
	}
}

func (m *defaultLogIngester) WriteLog(ctx context.Context, in *WriteLogReq, opts ...grpc.CallOption) (*WriteLogResp, error) {
	client := ingester.NewLogIngesterClient(m.cli.Conn())
	return client.WriteLog(ctx, in, opts...)
}
